Webim_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('auth_vk.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

auth_vk/urls.py
from django.urls import path

from .views import *

app_name='auth_vk'
urlpatterns = [
    # Выход
    path('accounts/logout/', VKLogoutView.as_view(), name='logout'),
    # Главная
    path('', index, name='index')
]

auth_vk/models.py
from django.db import models

# Create your models here.

auth_vk/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
import utilities

# Главная страница
def index(request):
    if request.user.is_authenticated:
        friends = utilities.friends(request.user)
        return render(request, 'auth_vk/index.html', context={'friends': friends})
    else:
        return render(request, 'auth_vk/index.html')

# Выход
class VKLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'auth_vk/index.html'

auth_vk/templates/auth_vk/index.html
{% extends "layout/basic.html" %}

{% load account socialaccount %}

{% block content%}

{% if user.is_authenticated %}
<a href="{% url 'auth_vk:logout' %}">Выйти</a>
<h2 class="text-center">{% user_display user %}</h2>

{% for friend in friends %}
<div class="border"><a href="https://vk.com/{{ friend.domain }}" target="_blank">
        <img src="{{ friend.photo_100 }}">
        {{ friend.first_name }} {{ friend.last_name }}
    </a></div>
{% endfor %}

{% else %}
<p class="text-center"><a class="btn btn-primary" href="{% provider_login_url "vk" %}">Авторизоваться</a></p>
{% endif %}

{% endblock %}

auth_vk/templates/layout/basic.html
{% load bootstrap4 %}
{% load static%}
<html>
	<head>
		<meta http-equiv="Content-Type"
		content="text/html; charset=utf-8">
		<meta name="viewport"
		content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}Главная{% endblock %}</title>
		{% bootstrap_css %}
		{% bootstrap_javascript jquery='slim' %}
	</head>
	<body class="container-fluid">
		<header class="mb-4">
			<h1 class="display-4 text-center">Авторизация вконтакте</h1>
		</header>
		<section class="col py-2 transparent">
				{% bootstrap_messages %}
				{% block content %}
				{% endblock %}
			</section>
		</div>
		<footer class="mt-3">
		</footer>
	</body>
</html>